name: build_wintools
on:
  push: {tags:  ['v*'] } # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request: 

permissions:
  contents: write
  
jobs:
  build_winexe_winmemdll:
    runs-on: windows-2025
    steps:
    - name: pull and init
      uses: actions/checkout@v3
      with: {submodules: true}
    
    - name: add msbuild to path
      uses: microsoft/setup-msbuild@v1.1
    
    - name: prepare enviroment
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $WorkLoads = '--add Microsoft.VisualStudio.Component.WinXP'
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"", $WorkLoads, '--quiet', '--norestart', '--nocache')
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        if ($process.ExitCode -eq 0)
        {
            Write-Host "components have been successfully added"
        }
        else
        {
            Write-Host "components were not installed"
            exit 1
        }

    - name: build target
      run: script/build_winmemdll.bat
    
    - name: upload release
      uses: ncipollo/release-action@v1
      if: github.event_name == 'push'
      with:
        artifacts: "build/winmemdll32.exe,build/winmemdll64.exe"
        allowUpdates: "true"
        token: ${{ secrets.GITHUB_TOKEN }}